services:
  postrgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_DB: project
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
    ports:
        - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
 